### ISSUE TITLE
Error when using fetcher.py

### ISSUE THREAD

**Issue by gpxlnx** [reddelexc/hackerone-reports#15]
When I run fetcher.py the message error below show me:

Page: 1
Traceback (most recent call last):
  File "/tmp/hackerone-reports/fetcher.py", line 97, in <module>
    fetch()
  File "/tmp/hackerone-reports/fetcher.py", line 83, in fetch
    next_page_button.click()
  File "/home/gxavier/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py", line 94, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/gxavier/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
  File "/home/gxavier/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "/home/gxavier/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button data-testid="hacktivity-next-button" class="Button-module_u1-button__OJmLM Button-module_u1-button--tertiary__LpDOx Button-module_u1-button--rounded-all__h9prY">...</button> is not clickable at point (731, 476). Other element would receive the click: <div class="fixed top-0 left-0 w-screen h-screen"></div>
  (Session info: chrome-headless-shell=127.0.6533.72)
Stacktrace:
#0 0x5649b675c6ba <unknown>
#1 0x5649b642c730 <unknown>
#2 0x5649b6482a96 <unknown>
#3 0x5649b64809ad <unknown>
#4 0x5649b647e447 <unknown>
#5 0x5649b647d30e <unknown>
#6 0x5649b6470d66 <unknown>
#7 0x5649b649ea52 <unknown>
#8 0x5649b6470719 <unknown>
#9 0x5649b649ec1e <unknown>
#10 0x5649b64bd1ca <unknown>
#11 0x5649b649e7f3 <unknown>
#12 0x5649b646eec9 <unknown>
#13 0x5649b646f91e <unknown>
#14 0x5649b67229eb <unknown>
#15 0x5649b6726972 <unknown>
#16 0x5649b670fe15 <unknown>
#17 0x5649b6727502 <unknown>
#18 0x5649b66f4d2f <unknown>
#19 0x5649b674b578 <unknown>
#20 0x5649b674b750 <unknown>
#21 0x5649b675b48c <unknown>
#22 0x7db6f8c94ac3 <unknown>

I'm using Ubuntu 22.04, python 3.10. I tried to ran using venv but not works.

**Comment by reddelexc** [comment]
i reproduced it, trying to figure it out...

**Comment by reddelexc** [comment]
@gpxlnx hey, I pushed the fix to master, please pull changes and check if error still there

**Comment by gpxlnx** [comment]
@reddelexc Thanks for your support. Its works to me. Thanks
